version: "3.9"

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: shopping_app
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
    volumes:
      - ./schema/shopping-app-init.sql:/docker-entrypoint-initdb.d/shopping-app-init.sql
    
  backend:
    build: 
        context: .
        dockerfile: backend/Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always